# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'Rango' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Rango
  pod 'R.swift'
  pod 'Nuke'
  pod 'Nimble'
  pod 'Quick'

  target 'RangoTests' do
    inherit! :search_paths

  end

end
